<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('19', '/uploads/141113/1-1411131A103605.jpg');
$maNum = 1;
$myaddons[$maNum] = array('20', '/uploads/141113/1-1411131A13G54.jpg');
$maNum = 2;
$myaddons[$maNum] = array('21', '/uploads/141113/1-1411131A632b6.jpg');
$maNum = 3;
$myaddons[$maNum] = array('22', '/uploads/141113/1-1411131AH1932.jpg');
$maNum = 4;
$myaddons[$maNum] = array('23', '/uploads/141113/141113/1-1411131G00KJ.jpg');
$maNum = 5;
$myaddons[$maNum] = array('24', '/uploads/141113/141113/1-1411131G05b95.jpg');
$maNum = 6;
