<div class="learnchapter  learnchapter-active ">
        <h3> <span>-</span> <strong><i class="hasOpenOn"></i> {dede:field name='typename'/}</strong> </h3>
        
        <ul class="video">
			 {dede:arclist titlelen='42' row='10'} 
            <li> <a target="_blank" href="[field:arcurl/]" class="studyvideo"> [field:title /] <i></i> </a> </li>
            {/dede:arclist}
          </ul>
    </div>