<li class="course-one">
    <a href="[field:arcurl/]">
        <div class="course-list-img">
        	<img width="240" height="135" alt="[field:title/]" src="[field:litpic/]">
        </div>
    	<h5><span>[field:title/]</span> </h5>
        <div class="tips">
            <p class="text-ellipsis">[field:description/]</p>
            <span class="l update-latest">[field:lastupdate/]</span>
            <span class="l ml20">[field:click/]人学习</span>
        </div>
        <span class="time-label">[field:coursetime/]</span>
        <b class="follow-label">跟我学</b>
</a>
</li>