<?php
$z[0]=Array("field","",15,43);
$z[0][4]['name']="typeurl";
$z[1]=Array("typename"," \r\n                       @me = preg_replace(\"|[a-z]|is\",\"\",@me); \r\n                    ",67,199);
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n	                   <span> <a href=\"[field:typelink/]\">{dede:typename runphp='yes'} \r\n                       @me = preg_replace(\"|[a-z]|is\",\"\",@me); \r\n                    {/dede:typename}</a></span>\r\n                         ",251,531);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>