<?php
$z[0]=Array("spaceurl","",90,108);
$z[1]=Array("face","",137,150);
$z[2]=Array("spaceurl","",197,215);
$z[3]=Array("uname","",234,248);
$z[4]=Array("spaceurl","",298,316);
$z[5]=Array("spaceurl","",394,412);
$z[6]=Array("spaceurl","",483,501);
$z[7]=Array("lovemsg","",566,582);
$z[8]=Array("rankname","",661,679);
$z[9]=Array("jointime","",747,799);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[10]=Array("logintime","",867,920);
$z[10][4]['function']="MyDate('Y-m-d H:m',@me)";

?>