<div class="learnchapter  learnchapter-active ">
  <h3> <span>-</span> <strong><i class="hasOpenOn"></i>{dede:field name='typename'/}</strong> </h3>
  
  <ul class="video">
   {dede:arclist titlelen='42' row='10'} 
    <li> <em class="laststudy">最近学习</em> <a target="_blank" href="/video/5673" class="studyvideo">[field:title /] (01:27) <i class="hasStudy">([field:pubdate function="MyDate('m-d',@me)"/])</i> </a> </li>
</ul>

</div>