<?php
$z[0]=Array("filename","",197,214);
$z[1]=Array("picname","",242,259);
$z[2]=Array("filename","",431,448);
$z[3]=Array("title","",515,529);
$z[4]=Array("title","",553,567);
$z[5]=Array("pubdate","",649,702);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",791,808);
$z[7]=Array("info","",883,896);
$z[8]=Array("writer","",1009,1024);
$z[9]=Array("click","",1090,1104);

?>