<?php
$z[0]=Array("filename","",185,202);
$z[1]=Array("picname","",230,247);
$z[2]=Array("filename","",399,416);
$z[3]=Array("title","",472,486);
$z[4]=Array("title","",510,524);
$z[5]=Array("pubdate","",606,659);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",739,756);
$z[7]=Array("info","",831,844);
$z[8]=Array("writer","",946,961);
$z[9]=Array("click","",1027,1041);

?>