<?php
$z[0]=Array("filename","",142,159);
$z[1]=Array("picname","",187,204);
$z[2]=Array("filename","",356,373);
$z[3]=Array("title","",429,443);
$z[4]=Array("title","",467,481);
$z[5]=Array("pubdate","",563,616);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",696,713);
$z[7]=Array("info","",773,786);
$z[8]=Array("writer","",888,903);
$z[9]=Array("click","",969,983);

?>