<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:coursetime itemname="课程时长" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default="30分钟"  maxlength="250" page="">
</field:coursetime>

<field:teacher itemname="讲师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="曾庆林"  maxlength="250" page="">
</field:teacher>

<field:teacherinfo itemname="讲师简介" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="6年教学经验，已培养近千名优秀UI设计师，被学员爱称为“木木”老师。授课生动形象、机智诙谐、有条不紊、声音洪亮、穿透力十足"  maxlength="250" page="">
</field:teacherinfo>


<field:lastupdate itemname="课程更新到" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="完成"  maxlength="250" page="">
</field:lastupdate>

<field:level itemname="课程难度" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="0,1,2,3"  maxlength="250" page="">
</field:level>
