<li class="course-one">
    <a href="[field:arcurl/]">
        <div class="course-list-img">
        	<img width="240" height="135" alt="[field:title/]" src="[field:litpic/]">
        </div>
    	<h5><span>[field:title/]</span> </h5>
        <div class="tips">
            <p class="text-ellipsis">[field:description/]</p>
            <span class="l update-latest">[field:update/]</span>
            <span class="l ml20">[field:click/]人学习</span>
        </div>
        <span class="time-label">[field:coursetime/]</span>
        <b class="follow-label">跟我学</b>
</a>
</li>
{/dede:list}
                                  
                                           
          
        </ul>
      
    
  </div>
  <!--page-->
  <div class="page"><span class="disabled_page">首页</span><span class="disabled_page">上一页</span><a href="javascript:void(0)" class="active">1</a><a href="/course/list?page=2">2</a><a href="/course/list?page=3">3</a><a href="/course/list?page=4">4</a><a href="/course/list?page=5">5</a><a href="/course/list?page=6">6</a><a href="/course/list?page=7">7</a><a href="/course/list?page=2">下一页</a><a href="/course/list?page=17">尾页</a></div>
    <!--page-->
</div>
</div>


  <!--课程-->

 {dede:include filename="qkt_footer.htm"