<a style="width: 175px; height: 130.677px;" class="Portfolio_small" href="[field:filename/]">                
                  <figure style="width: 172px; height: 127.677px;" class="pimg"><img src="[field:picname/]"></figure>
                  
                  <div style="width: 172px; height: 127.677px;" class="PRO_back">
                    <figure><img src="[field:picname/]" alt="forte"></figure>                      
                </div>
                  </a>