<?php
$z[0]=Array("filename","",145,162);
$z[1]=Array("picname","",190,207);
$z[2]=Array("filename","",365,382);
$z[3]=Array("title","",414,428);
$z[4]=Array("title","",452,466);
$z[5]=Array("pubdate","",551,604);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",687,704);
$z[7]=Array("info","",722,735);
$z[8]=Array("writer","",816,831);
$z[9]=Array("click","",897,911);

?>