<?php
$z[0]=Array("type","\r\n         <h3><a href=\"[field:typelink /]\">>> [field:typename /]</a></h3>\r\n   ",24,126);
$z[1]=Array("arclist","\r\n            <li><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span><a href=\"[field:arcurl /]\" title=\"[field:title function='html2text(@me)'/]\">[field:title function=' ( strlen(\"@me\")>40 ? cn_substr(\"@me\",40): \"@me\" ) '/]</a></li>\r\n        ",145,447);
$z[1][4]['row']="8";
$z[1][4]['titlelen']="100";

?>