<?php
$z[0]=Array("filename","",185,202);
$z[1]=Array("picname","",230,247);
$z[2]=Array("filename","",419,436);
$z[3]=Array("title","",492,506);
$z[4]=Array("title","",530,544);
$z[5]=Array("pubdate","",626,679);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",798,815);
$z[7]=Array("info","",890,903);
$z[8]=Array("writer","",1005,1020);
$z[9]=Array("click","",1086,1100);

?>