<?php
$z[0]=Array("filename","",197,214);
$z[1]=Array("picname","",242,259);
$z[2]=Array("filename","",431,448);
$z[3]=Array("title","",504,518);
$z[4]=Array("title","",542,556);
$z[5]=Array("pubdate","",638,691);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",780,797);
$z[7]=Array("info","",872,885);
$z[8]=Array("writer","",998,1013);
$z[9]=Array("click","",1079,1093);

?>