<?php
$z[0]=Array("filename","",141,158);
$z[1]=Array("picname","",186,203);
$z[2]=Array("filename","",353,370);
$z[3]=Array("title","",402,416);
$z[4]=Array("title","",440,454);
$z[5]=Array("pubdate","",535,588);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",667,684);
$z[7]=Array("info","",702,715);
$z[8]=Array("writer","",792,807);
$z[9]=Array("click","",873,887);

?>