<?php
$z[0]=Array("field","",18,47);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","      \r\n         <li cid=\"112852\" class=\"\">\r\n           <a onclick=\"\" href=\"[field:arcurl/]\" class=\"chac\" id=\"classitem_112852\" clsitm=\"1\">\r\n             <div class=\"l_j\">[field:title /]</div>           \r\n           </a>\r\n         </li>  \r\n          ",78,380);
$z[1][4]['titlelen']="42";
$z[1][4]['row']="10";

?>