<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:coursetime itemname="课程时长" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:coursetime>


<field:teacher itemname="授课老师" autofield="1" notsend="0" type="textchar" isnull="true" islist="0" default="曾庆林"  maxlength="250" page="">
</field:teacher>

<field:teacherinfo itemname="老师简介" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:teacherinfo>


<field:material itemname="资料下载" autofield="1" notsend="0" type="addon" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:material>

<field:level itemname="文章难度" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="0,1,2,3"  maxlength="250" page="">
</field:level>

<field:update itemname="更新" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default="完毕"  maxlength="250" page="">
</field:update>
