<?php
$z[0]=Array("filename","",198,215);
$z[1]=Array("picname","",243,260);
$z[2]=Array("filename","",432,449);
$z[3]=Array("title","",505,519);
$z[4]=Array("title","",543,557);
$z[5]=Array("pubdate","",639,692);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",781,798);
$z[7]=Array("info","",873,886);
$z[8]=Array("writer","",988,1003);
$z[9]=Array("click","",1069,1083);

?>