<span><a href="{dede:field name='typeurl'/}">
                    {dede:typename runphp='yes'} 
                       @me = preg_replace("|[a-z]|is","",@me); 
                    {/dede:typename}</a></span>
	                
                    {dede:channel type='son' noself='yes'}
	                   <span> <a href="[field:typelink/]">
                      {dede:typename runphp='yes'} 
                       @me = preg_replace("|[a-z]|is","",@me); 
                    {/dede:typename}</a></span>
                         {/dede:channel}