<div class="teacher-block c-bg">
      <h3>授课老师</h3>

      <p class="t-name"><a href="#" class="t-pic"><img src="[field:face/]" width="80"></a><a href="#">[field:uname/]</a></p>
      <div class="t-discrip">[field:lovemsg/]</div>
    </div><!--blocked-->
    
    <div class="teacher-block  c-bg">
      <h3>资料下载</h3>
      <ul class="downlist">
                <li>
          <span><i class="icon icon-folder"></i>下载资料</span>
          {dede:field name='softlinks'/}
        </li>
                
            </ul> 
    </div><!--bocked--->