<li style="overflow: hidden; height: 70px;" class="inCaseli">
        <div class="inCaseImg"> 
        <ul>
        
        {dede:channelartlist   typeid='12'}
	            <li class="ab_list"><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></li>               
	                
                              
                {/dede:channelartlist}
        	
        </ul>
        <img style="width: 1024px; height: 416px; left: 0px; top: -173px;" src="[field:hbigpic/]" class="inCaseimgB" height="650" width="1600">
          <div style="opacity: 1;" class="inCase_btn"><a href="javascript:;"> <img src='[field:hspic/]'/> </a></div>
          <article style="display: none; opacity: 0;" class="inCase_MoreInfo">
            <div class="inCase_infoBox">
              <h1>[field:title/]</h1>
              [field:hdes/] <a class="inCase_infoClose"></a> </div>
          </article>
        </div>
        <div class="Pic_hide">
          <div class="Pic_hide2"> <a class="Pic_hideJT"></a></div>
        </div>
      </li>