<section style="width: 370px; margin-left: 15px; margin-right: 15px; margin-bottom: 30px;" class="ideas_li ">
                  <figure><a href="[field:filename/]" target="_blank"><img src='[field:picname /]' border='0' width='' height=''/><span class="ideaPz"></span></a> </figure>
                  <div style="width: 150px;">
                    <h1><a href="[field:filename/]" class="ideaTitle" data-hover="[field:title/]" target="_blank"><span>[field:title/]</span></a></h1>
                    <p class="txt-10px color3b3b3b paddingBottom10">[field:pubdate function='strftime("%b %d, %Y",@me)'/]</p>
                    <p class=" txt-12px color3b3b3b paddingBottom10"><a href="[field:filename/]" target="_blank">[field:info/]</a></p>
                    <p class="color3b3b3b"><span class="ideas_zuanzai ">[field:writer/]&nbsp;&nbsp;|&nbsp;&nbsp;<span class="ideas_zuanzai">热度</span>[field:click/]</span></p>
                  </div>
                </section>