<?php
$z[0]=Array("filename","",146,163);
$z[1]=Array("picname","",191,208);
$z[2]=Array("filename","",365,382);
$z[3]=Array("title","",414,428);
$z[4]=Array("title","",452,466);
$z[5]=Array("pubdate","",552,605);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",689,706);
$z[7]=Array("info","",724,737);
$z[8]=Array("writer","",819,834);
$z[9]=Array("click","",900,914);

?>