<li style="height:400px;" class="joblist">
                        <div class="view overlay" style="background-image:url(../image/about/job01.jpg)">
                            <div class="mask" style="">
                            
                                <h3 style="color:#181818; border:0;"><b>[field:title/]</b></h3><br/><br/>
                                
                                <p style="color:#181818">
                                [field:description/]
                                
                                <br/><br/><br/>
								<a href="mailto:{dede:global.cfg_coemail/}">发送简历和作品 </a><br/>
                                <a href="[field:arcurl/]">产看详情</a>
								
								</p>
									
                            </div>
                        </div>
                    </a>    
                </li>