<?php
$z[0]=Array("filename","",142,159);
$z[1]=Array("picname","",187,204);
$z[2]=Array("filename","",356,373);
$z[3]=Array("title","",405,419);
$z[4]=Array("title","",443,457);
$z[5]=Array("pubdate","",539,592);
$z[5][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[6]=Array("filename","",672,689);
$z[7]=Array("info","",707,720);
$z[8]=Array("writer","",798,813);
$z[9]=Array("click","",879,893);

?>