<?php
$z[0]=Array("link"," https://raw.githubusercontent.com/zengqinglin/qingkt/master/AxureRP7.0%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A.mp4 ",0,179);
$z[0][4]['islocal']="1";
$z[0][4]['text']="普清";
$z[1]=Array("link"," https://raw.githubusercontent.com/zengqinglin/qingkt/master/AxureRP7.0%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A.mp4 ",181,348);
$z[1][4]['text']="标清";

?>