<li style="overflow: hidden; height: 70px;" class="inCaseli">
        <div class="inCaseImg"> 
        <ul>
      <p class="about_nr"> <a href="{dede:global.cfg_basehost/}/a/service/" target="_blank"> <img src="images/ideapicr.png" height="484" width="603"></a></p>
    </div>
  </div>
  <div style="height: 310px; width: 212.594px;" class="about_right">
    <div style="right: 212.594px; bottom: 0px;" class="about_jt">
      <p class="about_jt1"><a></a></p>
      <p class="about_jtNumber">1/3</p>
      <p class="about_jt2"><a></a></p>
    </div>
    <div style="height: 310px; width: 212.594px;" class="about_picBox">
      <div style="opacity: 1; margin-top: 0px; width: 212.594px;" class="about_picall"> {dede:arclist addfields="hapic"  channelid="18"} <img style="height: 310px; width: 212.594px;" src=" [field:hapic/]" class="about_picli">