<?php
$z[0]=Array("global","",76,108);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_coemail";
$z[2]=Array("global","",474,499);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",499,526);
$z[3][4]['name']="cfg_cowbxpic";
$z[4]=Array("global","",691,716);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",716,740);
$z[5][4]['name']="cfg_wxpic";
$z[6]=Array("global","",1006,1033);
$z[6][4]['name']="cfg_coweibox";
$z[7]=Array("global","",1343,1370);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("channelartlist","\r\n	          \r\n	                <span><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></span>\r\n	                \r\n                    {dede:channel type='son' noself='yes'}\r\n	                   <span> <a href=\"[field:typelink/]\">[field:typename/]</a></span>\r\n                         {/dede:channel}\r\n	           \r\n                ",1402,1815);
$z[8][4]['typeid']="top";
$z[9]=Array("global","",2297,2324);
$z[9][4]['name']="cfg_indexurl";
$z[10]=Array("global","",2336,2368);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",2723,2755);
$z[11][4]['name']="cfg_templets_skin";

?>