<?php
$z[0]=Array("global","",103,130);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",142,174);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",331,358);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("channelartlist","\r\n	            <li>\r\n	                <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n	                <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n	                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                         {/dede:channel}\r\n	                   \r\n                       \r\n	                </ul>\r\n	            </li>\r\n                ",377,860);
$z[3][4]['typeid']="top";

?>