<?php
$z[0]=Array("global","",246,278);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",329,361);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",454,479);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("arclist","    \r\n<li class=\"course-one\">\r\n    <a href=\"[field:arcurl/]\">\r\n        <div class=\"course-list-img\">\r\n        	<img width=\"240\" height=\"135\" alt=\"[field:title/]\" src=\"[field:litpic/]\">\r\n        </div>\r\n    	<h5><span>[field:title/]</span> </h5>\r\n        <div class=\"tips\">\r\n            <p class=\"text-ellipsis\">[field:shorttitle/]</p>\r\n            <span class=\"l update-latest\">[field:color/]</span>\r\n            <span class=\"l ml20\">[field:click/]人学习</span>\r\n        </div>\r\n        <span class=\"time-label\">[field:softsize/]</span>\r\n     <!--   <b class=\"follow-label\">跟我学</b>-->\r\n</a>\r\n</li>\r\n",5661,6370);
$z[3][4]['infolen']="52";
$z[3][4]['typeid']="12";
$z[3][4]['addfields']="softsize";
$z[3][4]['row']="12";
$z[3][4]['channelid']="17";
$z[4]=Array("global","",7600,7632);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",7676,7708);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",8345,8373);
$z[6][4]['name']="cfg_memberurl";
$z[7]=Array("php","\r\n        if(preg_match(\"#2#\", \$safe_gdopen))\r\n        {\r\n        echo '\r\n        <div class=\"form-group clearfix\" >\r\n       \r\n         <input type=\"text\" name=\"vdcode\" size=\"8\" class=\"ipt ipt-verify l\" placeholder=\"请输入验证码\" />\r\n           <a href=\"javascript:void(0)\" class=\"verify-img-wrap js-verify-refresh\"> <img id=\"vdimgck\" align=\"absmiddle\" onClick=\"this.src=this.src+\\'?\\'\" style=\"cursor:pointer;margin-left:0px;text-transform:uppercase;\" alt=\"看不清？点击更换\" src=\"'.\$cfg_cmspath.'/include/vdimgck.php\" width=\"100\"/>\r\n           </a><span class=\"verify-extra r\"> 看不清<br>\r\n         <a href=\"javascript:void(0)\"  onclick=\"changeAuthCode(\\'#vdimgck\\');\"  class=\"js-verify-refresh\">换一张</a> </span>\r\n            <p class=\"rlf-tip-wrap\"> <span style=\"display: none;\">请输入右侧图片内容</span> </p>\r\n         </div> \r\n        ';\r\n        }\r\n       \r\n        ",9162,10084);
$z[8]=Array("global","",10582,10610);
$z[8][4]['name']="cfg_memberurl";
$z[9]=Array("global","",10837,10863);
$z[9][4]['name']="cfg_cmspath";
$z[10]=Array("php","\r\n        if(preg_match(\"#2#\", \$safe_gdopen))\r\n        {\r\n        echo '\r\n        <div class=\"form-group clearfix\" >\r\n       \r\n         <input type=\"text\" name=\"vdcode\" size=\"8\" class=\"ipt ipt-verify l\" placeholder=\"请输入验证码\" />\r\n           <a href=\"javascript:void(0)\" class=\"verify-img-wrap js-verify-refresh\"> <img id=\"vdimgck2\" align=\"absmiddle\" onClick=\"this.src=this.src+\\'?\\'\" style=\"cursor:pointer;margin-left:0px;text-transform:uppercase;\" alt=\"看不清？点击更换\" src=\"'.\$cfg_cmspath.'/include/vdimgck.php\" width=\"100\"/>\r\n           </a><span class=\"verify-extra r\"> 看不清<br>\r\n         <a href=\"javascript:void(0)\"  onclick=\"changeAuthCode(\\'#vdimgck2\\');\"  class=\"js-verify-refresh\">换一张</a> </span>\r\n            <p class=\"rlf-tip-wrap\"> <span style=\"display: none;\">请输入右侧图片内容</span> </p>\r\n         </div> \r\n        ';\r\n        }\r\n       \r\n        ",12591,13515);
$z[11]=Array("global","",14441,14466);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("global","",14559,14585);
$z[12][4]['name']="cfg_cmspath";
$z[13]=Array("global","",14642,14668);
$z[13][4]['name']="cfg_cmspath";
$z[14]=Array("global","",14940,14966);
$z[14][4]['name']="cfg_cmspath";
$z[15]=Array("global","",15208,15236);
$z[15][4]['name']="cfg_mb_pwdmin";

?>