<?php
$z[0]=Array("global","",1744,1776);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1820,1852);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2489,2517);
$z[2][4]['name']="cfg_memberurl";
$z[3]=Array("php","\r\n        if(preg_match(\"#2#\", \$safe_gdopen))\r\n        {\r\n        echo '\r\n        <div class=\"form-group clearfix\" >\r\n       \r\n         <input type=\"text\" name=\"vdcode\" size=\"8\" class=\"ipt ipt-verify l\" placeholder=\"请输入验证码\" />\r\n           <a href=\"javascript:void(0)\" class=\"verify-img-wrap js-verify-refresh\"> <img id=\"vdimgck\" align=\"absmiddle\" onClick=\"this.src=this.src+\\'?\\'\" style=\"cursor:pointer;margin-left:0px;text-transform:uppercase;\" alt=\"看不清？点击更换\" src=\"'.\$cfg_cmspath.'/include/vdimgck.php\" width=\"100\"/>\r\n           </a><span class=\"verify-extra r\"> 看不清<br>\r\n         <a href=\"javascript:void(0)\"  onclick=\"changeAuthCode(\\'#vdimgck\\');\"  class=\"js-verify-refresh\">换一张</a> </span>\r\n            <p class=\"rlf-tip-wrap\"> <span style=\"display: none;\">请输入右侧图片内容</span> </p>\r\n         </div> \r\n        ';\r\n        }\r\n       \r\n        ",3306,4228);
$z[4]=Array("global","",4726,4754);
$z[4][4]['name']="cfg_memberurl";
$z[5]=Array("global","",4981,5007);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("php","\r\n        if(preg_match(\"#2#\", \$safe_gdopen))\r\n        {\r\n        echo '\r\n        <div class=\"form-group clearfix\" >\r\n       \r\n         <input type=\"text\" name=\"vdcode\" size=\"8\" class=\"ipt ipt-verify l\" placeholder=\"请输入验证码\" />\r\n           <a href=\"javascript:void(0)\" class=\"verify-img-wrap js-verify-refresh\"> <img id=\"vdimgck2\" align=\"absmiddle\" onClick=\"this.src=this.src+\\'?\\'\" style=\"cursor:pointer;margin-left:0px;text-transform:uppercase;\" alt=\"看不清？点击更换\" src=\"'.\$cfg_cmspath.'/include/vdimgck.php\" width=\"100\"/>\r\n           </a><span class=\"verify-extra r\"> 看不清<br>\r\n         <a href=\"javascript:void(0)\"  onclick=\"changeAuthCode(\\'#vdimgck2\\');\"  class=\"js-verify-refresh\">换一张</a> </span>\r\n            <p class=\"rlf-tip-wrap\"> <span style=\"display: none;\">请输入右侧图片内容</span> </p>\r\n         </div> \r\n        ';\r\n        }\r\n       \r\n        ",6735,7659);
$z[7]=Array("global","",8585,8610);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",8703,8729);
$z[8][4]['name']="cfg_cmspath";
$z[9]=Array("global","",8786,8812);
$z[9][4]['name']="cfg_cmspath";
$z[10]=Array("global","",9084,9110);
$z[10][4]['name']="cfg_cmspath";
$z[11]=Array("global","",9352,9380);
$z[11][4]['name']="cfg_mb_pwdmin";

?>