<?php
$z[0]=Array("field","",436,455);
$z[0][4]['name']="title";
$z[1]=Array("global","",456,482);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",523,552);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",592,650);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",685,717);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",784,816);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",859,891);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",979,1011);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1066,1098);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1147,1179);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("include","",1426,1463);
$z[10][4]['filename']="headrm.htm";
$z[11]=Array("sql","\r\n<a href=\"[field:typedir/]\">[field:typename/]</a>\r\n",1707,1854);
$z[11][4]['sql']="SELECT `typedir`, `typename` FROM `rm_arctype` WHERE `id`=~typeid~";
$z[12]=Array("field","",2003,2032);
$z[12][4]['name']="position";
$z[13]=Array("sql","\r\n[field:typename/]\r\n",2182,2298);
$z[13][4]['sql']="SELECT `typedir`, `typename` FROM `rm_arctype` WHERE `id`=~typeid~";
$z[14]=Array("field","",2380,2399);
$z[14][4]['name']="title";
$z[15]=Array("field","",2434,2452);
$z[15][4]['name']="body";
$z[16]=Array("include","",2484,2523);
$z[16][4]['filename']="footerrm.htm";

?>